title: My Sketchbook
description: A gallery of generative animations and visualizations, built with p5.js.
baseurl: "/vizu"   
url: "https://shnmyklsnc.github.io"       

collections:
  sketches:
    output: true
    permalink: /sketches/:name/

defaults:
  - scope:
      path: ""
      type: sketches
    values:
      layout: sketch

markdown: kramdown
